openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of AquaTrack app
tags:
  - name: Students
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:8080,
  - url: https://back-inter-mafia.onrender.com/api/v1
paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
